config/routes.rb
Rails.application.routes.draw do
  resources :collaborators
  resources :events
  root 'pages#home'
  get '/background', to: 'pages#background'
  get '/approach', to: 'pages#approach'
  get '/ai_design_research', to: 'pages#ai_design_research'
  get '/research_inspiration', to: 'pages#research_inspiration'
  get '/design_implications', to: 'pages#design_implications'
  get '/current_ai_projects', to: 'pages#current_ai_projects'
  get '/future_directions', to: 'pages#future_directions'
  get '/resources', to: 'pages#resources'
  get '/diagram', to: 'pages#diagram'
  get '/diagram_map', to: 'pages#diagram_map'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  validates :name, length: { minimum: 5, maximum: 30 }
end

app/models/event.rb
class Event < ApplicationRecord
  validates :event_name, presence: true, length: { maximum: 30 }
  validates :location, presence: true, length: { maximum: 100 }
  validates :date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_collaborator, only: [:show, :edit, :update, :destroy]

  # GET /collaborators
  def index
    @collaborators = Collaborator.all
  end

  # GET /collaborators/1
  def show
  end

  # GET /collaborators/new
  def new
    @collaborator = Collaborator.new
  end

  # GET /collaborators/1/edit
  def edit
  end

  # POST /collaborators
  def create
    @collaborator = Collaborator.new(collaborator_params)

    respond_to do |format|
      if @collaborator.save
        format.html { redirect_to @collaborator, notice: 'Collaborator was successfully created.' }
        format.json { render :show, status: :created, location: @collaborator }
      else
        format.html { render :new }
        format.json { render json: @collaborator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collaborators/1
  def update
    respond_to do |format|
      if @collaborator.update(collaborator_params)
        format.html { redirect_to @collaborator, notice: 'Collaborator was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /collaborators/1
  def destroy
    @collaborator.destroy
    respond_to do |format|
      format.html { redirect_to collaborators_url, notice: 'Collaborator was successfully destroyed.' }
    end
  end

  private

  def set_collaborator
    @collaborator = Collaborator.find(params[:id])
  end

  def collaborator_params
    params.require(:collaborator).permit(:type, :name, :website, :image)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /events/1
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:event_name, :location, :date, :address, :about)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def background
  end

  def approach
  end

  def ai_design_research
  end

  def research_inspiration
  end

  def design_implications
  end

  def current_ai_projects
  end

  def future_directions
  end

  def resources
  end

  def diagram
  end

  def diagram_map
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/collaborators/_form.html.erb
<%= simple_form_for @collaborator do |f| %>
  <%= f.input :type %>
  <%= f.input :name %>
  <%= f.input :website %>
  <%= f.input :image %>
<% end %>

app/views/collaborators/edit.html.erb
<div id="page_wrapper">
  <div class='lower'>
  <h1>Edit Collaborator</h1>
  <%= render 'form', collaborator: @collaborator %>
  <%= link_to 'Show', @collaborator %> |
  <%= link_to 'Back', collaborators_path %>
  </div>
</div>

app/views/collaborators/index.html.erb
<div class="pages col-md-9">
    <h1 id='header'>Collaborators</h1>
    <p id="notice"><%= notice %></p>

      <h4>A very special thanks to</h4>
      <h4>my academic advisor Elise Co!</h4>
      <p>Direct or Indirect work on Feminist AI Projects Revisited has been made possible by emotional, intellectual and/or content contributions from the following feminists and organizations:</p>

      <div class="col-md-6">
        <p>
        Alison Adam, Adrienne Adar, Sara Ahmed, Casey Anderson, Evelyn Arias, Erika Barbosa, Austin Beers, Adam Berros, Anne Burdick, Dara Blumenthal, Karen Ann Boren, Mary Jo Boren, Elizabeth Braithwaite, William Braithwaite, Don Brittain, Zachary Canter, Kelsey Carter, Rumman Chowdhury, Lee Cody, Stephanie Cedeno, Kora Colasuonno, Ivanna Coleman, Brittney Cottrell, Kate Crawford, Yvonne Cruz, Briana Dacoscos, Jen Diamond, Debra Do, Tim Durfee, Claire Evans, Rebecca Fiebrink, Laura Fisher, Shiveesh Fotedar, Damian Gill, Pamela Grieman, Noelle Griffis, Houston Guy, Marshall Hamachi, Donna Haraway, Katherine Hayles, Jean He, Shannon Herbert, Reichel Hertzler, Cathy Hillman, Leah Horgan, Yunqiao Huang, Reina Imagawa, Nicholas Jayanty, Amanda Jensen, Casey Kawahara, Olive Kimono, Sonia Kissin, Lena Klimas
        </p>
      </div>

      <div class="col-md-6">
        <p>Jake Klorman, Liz Krane, Jesse Kriss, Hsinyu Lin, Marnie Maton , Maja Mataric, TL Morris, Joanne McNeil, Jade Milan, Tara Milch, Laura Montoya, Christopher Miles, Saara Nafici, Fay Nafici, Sohrab Nafici, Amirah Noaman, Claire Le Nobel, Camilla Pizarro, Jenny Rodenhouse, Godiva Reisenbichler, Lillian Rust, Suzanne Rust, RJ Sakai, Jen Samson, Camila Sobral, Ginny Song, Amanda Stojanov, Lee Tusman, Nan Tsai, Astha Vagadia, Philip van Allen, Claudia Varon, Michaella Vu, Emily Walworth, Sayee Wang, Lauren Williams, Marion Wirsig, Jason Wong, Mike Wong, Lucas Wrench, Nicci Yin, Mimi Zeiger, Women Who Code, <a href="http://womenscenterforcreativework.com/">The Women’s Center for Creative Work</a>, <a href="http://www.crosscamp.us/site/locations/cross-campus-downtown-la.html?source=googleadwords&gclid=Cj0KEQjwzpfHBRC1iIaL78Ol-eIBEiQAdZPVKnZ5l_K8uWREx5EKNTBLdnxTcaq2iDbIUMAK8FoGiPUaAuUF8P8HAQ">Cross Campus DTLA</a>, <a href="http://www.altadenalibrary.org/">The Altadena Public Library</a>, <a href="http://machineproject.com/">Machine Project</a>
        </p>
      </div>
    <!--
      <h2>Individual Collaborators</h2>
      <p>These individuals have either inspired or directly contributed to Bits and Bytes collaboartive AI.</p>
      <table>
        <thead>
          <tr>
            <th>Type</th>
            <th>Name</th>
            <th>Website</th>
            <th>Image</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <%# @collaborators.each do |collaborator| %>
            <tr>
              <td><%#= collaborator.type %></td>
              <td><%#= collaborator.name %></td>
              <td><%#= collaborator.website %></td>
              <td><%#= collaborator.image %></td>
              <td><%#= link_to 'Show', collaborator %></td>
              <td><%#= link_to 'Edit', edit_collaborator_path(collaborator) %></td>
              <td><%#= link_to 'Destroy', collaborator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% #end %>
        </tbody>
      </table>

      <h2>Organizations</h2>
      <p>These organizations have either inspired or directly contributed to Bits and Bytes collaboartive AI.</p>
      <br>
    -->
      <%#= link_to 'New Collaborator', new_collaborator_path %>

</div>

<%= image_tag 'icon1.png', class: 'randomly-placed-icon' %>
<%= image_tag 'icon2.png', class: 'randomly-placed-icon' %>
<%= image_tag 'icon3.png', class: 'randomly-placed-icon' %>

<script>
function rand0To100() {
  return Math.floor(Math.random() * 100);
}

$('.randomly-placed-icon').each(function() {
  $(this).css({top: rand0To100() + '%', left: rand0To100() + '%'});
});
</script>

app/views/collaborators/new.html.erb
<div id="page_wrapper">
  <div class='lower'>
    <h1>New Collaborator</h1>
    <%= render 'form', collaborator: @collaborator %>
    <%= link_to 'Back', collaborators_path %>
  </div>
</div>

app/views/collaborators/show.html.erb
<div id="page_wrapper">
  <div class='lower'>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Type:</strong>
    <%= @collaborator.type %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @collaborator.name %>
  </p>

  <p>
    <strong>Website:</strong>
    <%= @collaborator.website %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= @collaborator.image %>
  </p>

  <%= link_to 'Edit', edit_collaborator_path(@collaborator) %> |
  <%= link_to 'Back', collaborators_path %>
  </div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
  <%= f.input :event_name %>
  <%= f.input :location %>
  <%= f.input :address %>
  <%= f.input :date %>
  <%= f.input :about %>
  <%= f.button :submit %>
<% end %>

app/views/events/edit.html.erb
<div id="page_wrapper">
  <div class='lower'>
      <h1>Edit Event</h1>
      <%= render 'form', event: @event %>
      <%= link_to 'Show', @event %> |
      <%= link_to 'Back', events_path %>
  </div>
</div>

app/views/events/index.html.erb
<div class="pages col-md-9">
  <h1 id='header'>Events</h1>
  <p id="notice"><%= notice %></p>

  <div class="row">
    <% @events.each do |event| %>
      <div class="events col-sm-4 events">
        <h4><b><%= event.event_name %></b></h4>
        <p><%= event.location %><br/>
          <%= event.date.strftime("%B %-d, %Y") %></p>
      </div>
      <br/>
    <% end %>
  </div>
</div>

<%= image_tag 'icon1.png', class: 'randomly-placed-icon' %>
<%= image_tag 'icon2.png', class: 'randomly-placed-icon' %>
<%= image_tag 'icon3.png', class: 'randomly-placed-icon' %>
<%= image_tag 'icon1.png', class: 'randomly-placed-icon' %>
<%= image_tag 'icon2.png', class: 'randomly-placed-icon' %>
<%= image_tag 'icon3.png', class: 'randomly-placed-icon' %>
<script>
function rand0To100() {
  return Math.floor(Math.random() * 100);
}

$('.randomly-placed-icon').each(function() {
  $(this).css({top: rand0To100() + '%', left: rand0To100() + '%'});
});
</script>

app/views/events/new.html.erb
<div id="page_wrapper">
  <div class='lower'>
    <h1>New Event</h1>
    <%= render 'form', event: @event %>
    <%= link_to 'Back', events_path %>
  </div>
</div>

app/views/events/show.html.erb
<div id="page_wrapper">
  <div class='lower'>
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Event Name:</strong>
      <%= @event.event_name %>
    </p>

    <p>
      <strong>Location:</strong>
      <%= @event.location %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @event.address %>
    </p>

    <p>
      <strong>Date:</strong>
      <%= @event.date %>
    </p>

    <p>
      <strong>About:</strong>
      <%= @event.about %>
    </p>

    <%= link_to 'Edit', edit_event_path(@event) %> |
    <%= link_to 'Back', events_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FeministAi</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div class="content">
      <div class="under-shape-one"></div>
      <%= yield %>
      <!--<div class="under-shape-two"></div>-->
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

<!-- randomly-placed-icon -->

<%= image_tag 'icon1.png', class: 'randomly-placed-icon' %>
<%= image_tag 'icon2.png', class: 'randomly-placed-icon' %>
<%= image_tag 'icon3.png', class: 'randomly-placed-icon' %>

<script>
function rand0To100() {
  return Math.floor(Math.random() * 100);
}

$('.randomly-placed-icon').each(function() {
  $(this).css({top: rand0To100() + '%', left: rand0To100() + '%'});
});
</script>

app/views/pages/about.html.erb
<div class="pages col-md-9">
  <h1>BACKGROUND</h1>

<!--   <%= image_tag("about_feminist-artificial-intelligence_about_collaborative.jpg", alt: "Edit Entry", class:'images') %> -->
  <p>Feminist AI Projects Revisited is a product of Christine Meinders’ 2017 MFA thesis in Media Design Practices at ArtCenter College of
  Design. The first part of the research focused on sensory sociocultural experiences associated with embodiment, and the second part of
  the research focused on critical making as a response to hegemonic AI.</p>

  <p>Two Feminist AI Projects were designed to respond to this work: Bits & Bytes and the Posthuman Plugin Additional outcomes
  of the work include the AI Sociocultural Design Tool and video research explorations.</p>

<!-- <hr/> -->
<!--   <%= image_tag("about_feminist-artificial-intelligence_home_about_posthuman.jpg", alt: "Edit Entry", class:'images') %> -->
 <!--  <%= image_tag("about_feminist-artificial-intelligence_vive.jpg", alt: "Edit Entry", class:'images') %> -->
 <!--  <%= image_tag("about_feminist-artificial-intelligence_calendar.jpg", alt: "Edit Entry", class:'images') %> -->


  <p>To read research  click here for the first <%= link_to 'half of the working paper', 'https://drive.google.com/open?id=0Bz8lvCqH2p96NXdfc0VnaVF3QVk' %>.</p>

  <p><%= link_to 'Machine Project Presentation', 'https://drive.google.com/open?id=0Bz8lvCqH2p96STVWN3AzUVJoVFk' %> and video about Feminist AI Design, given at Machine Project on 4/1/17</p>

  <iframe src="https://player.vimeo.com/video/212216809" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
</div>

<%= image_tag 'icon1.png', class: 'randomly-placed-icon' %>
<%= image_tag 'icon2.png', class: 'randomly-placed-icon' %>
<%= image_tag 'icon3.png', class: 'randomly-placed-icon' %>

<script>
function rand0To100() {
  return Math.floor(Math.random() * 100);
}

$('.randomly-placed-icon').each(function() {
  $(this).css({top: rand0To100() + '%', left: rand0To100() + '%'});
});
</script>

app/views/pages/ai_design_tools.html.erb
<div class="pages col-md-9">
  <h1>INSIGHTS & IMPLICATIONS</h1>


<!--   <%= image_tag 'feminist-artificial-intelligence_design-research_insights.jpg', alt:'', class:'images' %> -->

  <h2>Insights</h2>
  <p>Findings based on research with the community through conversations, design investigations and questionnaires</p>
  <ul>
    <li>Participants reported that it is more interesting to have the ability to disable or modify learning behaviors in AI systems.</li>
    <li>Participants reported wanting the ability to directly expose social bias through material AI projects.</li>
    <li>Participants were interested in different approaches to AI, and felt that a mixing of approaches)
      such as symbolic and connectionist) might yield new thoughts about how to design AI systems.</li>
    <li>Participants were interested in designing with their own “little data” for curated intelligent experiences.</li>
    <li>When possible, participants wanted artificial intelligence to be to be housed in a physical form, which could serve as the interface.</li>
    <li>Participants wanted to “feel connected with (or be a part of) their environment” or “react to their environment” with their bodies.</li>
    <li>Users would like access to basic information about the AI system (such as supervised or unsupervised learning) and what data is being used.</li>
    <li>Users would like to be aware of both positive and negative bias that exists in AI systems.</li>
  </ul>

<hr/>

<h2>Implications</h2>
  <p>When utilizing Emotion, Sentiment, and Mood analysis in AI systems, designers should be trained by the individual or group of users, over time and should be changeable.</p>
  <ul>
    <li>Users should be able to disable or modify learning behaviors in AI systems.</li>
    <li>Users would like to use AI in for social critique and as a tool for collaboration with other humans.</li>
    <li>Users would like to design their own “little data” for curated intelligent experiences.</li>
    <li>Users should have control over the data that is put into the AI system.</li>
    <li>Users should be able to assign mix and match physical materials with learning algorithms.</li>
    <li>When applicable, should be able to use the form of the object as the interface.</li>
    <li>Designers should try to create AI systems that consider embodiment (not sure how to word this).</li>
    <li>Designers and developers should create AI systems that allow for physical or digital outcome (for things like political action).</li>
    <li>As designers we can use AI to identify, explore and expose both known and unknown bias, and can work with the community to create projects that reflect inequalities within groups and organizations.</li>
    <li>As designers we consider how to use to design for creative and embodied experiences.</li>
  </ul>

</div>


<%= image_tag 'icon1.png', class: 'randomly-placed-icon' %>
<%= image_tag 'icon2.png', class: 'randomly-placed-icon' %>
<%= image_tag 'icon3.png', class: 'randomly-placed-icon' %>

<script>
function rand0To100() {
  return Math.floor(Math.random() * 100);
}

$('.randomly-placed-icon').each(function() {
  $(this).css({top: rand0To100() + '%', left: rand0To100() + '%'});
});
</script>

app/views/pages/diagram.html.erb
<div class="diagram-page">
  <div class="outer-circle"></div> <!-- end outter circles -->
  <div class="inner-circle">
    <div class="arrows">
        <svg class="arrow1" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
             width="268.832px" height="268.832px" viewBox="0 0 268.832 268.832" style="enable-background:new 0 0 268.832 268.832;"
             xml:space="preserve">
        <g>
        <path d="M265.171,125.577l-80-80c-4.881-4.881-12.797-4.881-17.678,0c-4.882,4.882-4.882,12.796,0,17.678l58.661,58.661H12.5
              c-6.903,0-12.5,5.597-12.5,12.5c0,6.902,5.597,12.5,12.5,12.5h213.654l-58.659,58.661c-4.882,4.882-4.882,12.796,0,17.678
              c2.44,2.439,5.64,3.661,8.839,3.661s6.398-1.222,8.839-3.661l79.998-80C270.053,138.373,270.053,130.459,265.171,125.577z"/>
        </g>
        </svg>

        <svg class="arrow2" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
             width="268.832px" height="268.832px" viewBox="0 0 268.832 268.832" style="enable-background:new 0 0 268.832 268.832;"
             xml:space="preserve">
        <g>
        <path d="M265.171,125.577l-80-80c-4.881-4.881-12.797-4.881-17.678,0c-4.882,4.882-4.882,12.796,0,17.678l58.661,58.661H12.5
              c-6.903,0-12.5,5.597-12.5,12.5c0,6.902,5.597,12.5,12.5,12.5h213.654l-58.659,58.661c-4.882,4.882-4.882,12.796,0,17.678
              c2.44,2.439,5.64,3.661,8.839,3.661s6.398-1.222,8.839-3.661l79.998-80C270.053,138.373,270.053,130.459,265.171,125.577z"/>
        </g>
        </svg>

        <svg class="arrow3" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
          width="268.832px" height="268.832px" viewBox="0 0 268.832 268.832" style="enable-background:new 0 0 268.832 268.832;"
          xml:space="preserve">
          <g>
          <path d="M265.171,125.577l-80-80c-4.881-4.881-12.797-4.881-17.678,0c-4.882,4.882-4.882,12.796,0,17.678l58.661,58.661H12.5
              c-6.903,0-12.5,5.597-12.5,12.5c0,6.902,5.597,12.5,12.5,12.5h213.654l-58.659,58.661c-4.882,4.882-4.882,12.796,0,17.678
              c2.44,2.439,5.64,3.661,8.839,3.661s6.398-1.222,8.839-3.661l79.998-80C270.053,138.373,270.053,130.459,265.171,125.577z"/>
          </g>
        </svg>

        <svg class="arrow4" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
          width="268.832px" height="268.832px" viewBox="0 0 268.832 268.832" style="enable-background:new 0 0 268.832 268.832;"
          xml:space="preserve">
          <g>
          <path d="M265.171,125.577l-80-80c-4.881-4.881-12.797-4.881-17.678,0c-4.882,4.882-4.882,12.796,0,17.678l58.661,58.661H12.5
              c-6.903,0-12.5,5.597-12.5,12.5c0,6.902,5.597,12.5,12.5,12.5h213.654l-58.659,58.661c-4.882,4.882-4.882,12.796,0,17.678
              c2.44,2.439,5.64,3.661,8.839,3.661s6.398-1.222,8.839-3.661l79.998-80C270.053,138.373,270.053,130.459,265.171,125.577z"/>
          </g>
        </svg>
    </div> <!-- end arrows -->
    <div class="boxes">
      <div class="top-box diagram-boxes">
      <h3><%= link_to "input", diagram_map_path %></h3>
     </div>
      <br>
      <div class= "middle-box">
        <div class="diagram-boxes"><h3 class="model"><%= link_to "model", diagram_map_path %></h3></div>
        <div class="diagram-boxes"><h3><%= link_to "learning algorithm", diagram_map_path %></h3></div>
        <div class="diagram-boxes"><h3 class="tdat"><%= link_to "training data", diagram_map_path %></h3></div>
      </div>
      <br>
      <div class="bottom-box diagram-boxes"><h3><%= link_to "output", diagram_map_path %></h3></div>
    </div> <!-- end boxes -->
  </div> <!-- end inner circles -->
</div>



<div>
</div>

app/views/pages/diagram_map.html.erb
<section class="gradient">

<div class= "map-circles-top">
  <div class="shape1 map-circles buzz"><h4>hello</h4></div>
  <div class="shape2 map-circles"><h4>hello</h4></div>
  <div class="shape3 map-circles turn"><h4>hello</h4></div>
  <div class="shape4 map-circles"><h4>hello</h4></div>
</div>
<div class= "map-circles-bottom">
  <div class="shape5 map-circles"><h4>hello</h4></div>
  <div class="shape6 map-circles"><h4>hello</h4></div>
  <div class="shape7 map-circles"><h4>hello</h4></div>
  <div class="shape8 map-circles"><h4>hello</h4></div>
</div>

</section>

app/views/shared/_footer.html.erb
<footer>
  <%= link_to "Email", "mailto:christine.meinders@gmail.com" %> <br />
  <%= link_to 'Collaborators', collaborators_path %> <br />
  <%= link_to 'Resources', resources_path %> <br />
  <%= link_to 'Events', events_path %> <br />

<%= link_to "<i class='fa fa-facebook' aria-hidden='true'></i>".html_safe, "https://www.facebook.com/ReimaginingBitsAndBytes/" -%>&nbsp;
<%= link_to "<i class='fa fa-twitter' aria-hidden='true'></i>".html_safe, "https://twitter.com/bitsby-tes_la" -%>&nbsp;
<%= link_to "<i class='fa fa-calendar' aria-hidden='true'></i>".html_safe, events_path -%>&nbsp;
<%= link_to "<i class='fa fa-meetup' aria-hidden='true'></i>".html_safe, "https://www.meetup.com/Bits-and-Bytes-Feminist-Artificial-Intelligence-Projects/" -%>&nbsp;
<%= link_to "<i class='fa fa-tumblr' aria-hidden='true'></i>".html_safe, "http://reimagining-bits-and-bytes.tumblr.com/" -%>&nbsp;
<%= link_to "<i class='fa fa-instagram' aria-hidden='true'></i>".html_safe, "https://www.instagram.com/bitsbytesai/" -%>
</footer>

app/views/shared/_nav.html.erb
<nav>
  <div class="small-head">
   <h1><%= link_to "Feminist AI Projects Revisited", root_path %></h1>
  </div>

  <ul>
    <li><%= link_to 'Background', background_path %></li>
    <li><%= link_to 'Approach', approach_path %></li>
    <li><%= link_to 'Research Methods I', ai_design_research_path %></li>
     <li><%= link_to 'Research Methods II', research_inspiration_path %></li>
    <li><%= link_to 'Design Implications', design_implications_path %></li>
    <li><%= link_to 'Current Projects', current_ai_projects_path %></li>
    <li><%= link_to 'Future Directions', future_directions_path %></li>
<!--     <li><%= link_to 'Research Inspiration', research_inspiration_path %></li> -->
  </ul>
</nav>

app/views/shared/_navtop.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed nav-baby" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Feminist Artificial Intelligence Projects", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Design Philosophy', design_philosophy_path %></li>
        <li><%= link_to 'AI Design Research', ai_design_research_path %></li>
        <li><%= link_to 'AI Design Tools', ai_design_tools_path %></li>
        <li><%= link_to 'Current AI Projects', current_ai_projects_path %></li>
        <li><%= link_to 'About', about_path %></li>
      </ul>
    </div>
  </div>
</nav>